apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: auth-service
          image: Auth Image
          ports:
          - containerPort: 3001
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 2
              memory: 128Mi
          env:
          - name: NODE_ENV
            value: "production"