apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: gateway-service
          image: api-server Image URI 
          ports:
          - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 2
              memory: 256Mi
          env:
          - name: NODE_ENV
            value: "production"
