
apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-service
  template:
    metadata:
      labels:
        app: item-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: item-service
          image: Item Service Image
          ports:
          - containerPort: 3002
          resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 2
                memory: 128Mi
          env:
          - name: NODE_ENV
            value: "production"